---
kind: pipeline
type: exec
name: default

platform:
  os: macos
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  
trigger:
  branch:
    - main
  event:
    - pull_request
    - push


