---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands:
  - go build main.go
  - ./main
 

# trigger:
#   branch:
#     - main
#   event:
#     - pull_request
#     - push


